export const logo = 'https://www.logo.wine/a/logo/YouTube/YouTube-Logo.wine.svg'
export const humbergerMenu = 'https://i0.wp.com/css-tricks.com/wp-content/uploads/2012/10/threelines.png'
export const searchIcon = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Search_Icon.svg/750px-Search_Icon.svg.png?20181016161702'
export const voiceIcon = 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRhLoNSGoIqqmj8Z1MGwFPBS6TM_2MqpZkb25km6VNNU8kdG80M'
export const userIcon = 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png'
export const RES_IMAGE_URLs = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/'
export const RESLOGO = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf6NiwbeAg2gxo9w2vIMGfkHxPreEiCqoYhWUQ_b1j1AD2WJ7TV3DArt-ePGXFtRY9JX0&usqp=CAU'